@isTest
private class BusinessHoursControllerTest{
    /*@isTest
    private static void getBusinessHoursTest(){
        Test.startTest();
        //insert timeslot and call method with ID
        BusinessHoursController.getBusinessHours(null);
        Test.stopTest();
    }*/
    @isTest
    private static void BusinessHoursControllerTest(){
        Test.startTest();
        BusinessHoursController obj = new BusinessHoursController();
        Test.stopTest();
    }
      
}