/*
 * KRB - 20R3.0 Temp Excursion Calculation 
 * Class is used to store calculated fields used in Low Temp Assessment final Calculation
 * 
 * 
 * 
 */ 

public class MSD_CORE_CalcLowTempExcurExDetls {

    public Double hours = 0;
    public Double min = 0;
    public Double seconds = 0;
    public Double temp = 0;
    public Double calulatedUserEnteredExposureTimeHours = 0; 
    public Double calulatedUserEnteredExposureTimeMins = 0;
    public Double calulatedUserEnteredExposureTimeSeconds = 0;

}