public class Pw_Batch_Logger_Constants
{  
   
   public static final String BATCH_FAILURE = 'Batch Fail';
   public static final String BATCH_SUCCESS = 'Batch Success';
   public static final String BATCH_INCORRECT_SETTING = 'Batch Incorrect Setting';
   public static final String BATCH_NOEVENTS = 'Batch No Events';
   public static final String BATCH_GENERAL_EXCEPTION = 'Batch General Exception';

}